### ISSUE TITLE
Problem following along with custom metric walkthrough

### ISSUE THREAD

**Issue by jeffmartinxyz** [Azure/azure-k8s-metrics-adapter#47]
**Describe the bug**
When following the walkthrough for custom metrics, I get Error: release sample-release failed: customresourcedefinitions.apiextensions.k8s.io "custommetrics.azure.com" already exists

**To Reproduce**
Follow walkthrough until the helm install step.

**Expected behavior**
Since this is a walkthrough I expect the defaults to work out of the box, or for the walkthrough to inform me of what needs to be changed. (My apologies if this is obvious, still learning all the ins & outs of k8s)

**Kubernetes version (`kubectl version`):**
- [x] Running on AKS
```
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-24T06:54:59Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T17:53:03Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Logs (`kubectl logs <metric adapter pod id>`)**
See [error.txt](https://github.com/Azure/azure-k8s-metrics-adapter/files/2543583/error.txt)

**Additional context**
Following custom metrics walkthrough.

**Comment by jsturtevant** [comment]
This typically happens if you deployed the helm chart twice.  It is currently only possible to create a single instance of the metric adapter.  

```
helm install --name sample-release1 ../../charts/azure-k8s-metrics-adapter --namespace custom-metrics \
    --set appInsights.appId= \
    --set appInsights.key= \
    --set azureAuthentication.createSecret=true

helm install --name sample-release2 ../../charts/azure-k8s-metrics-adapter --namespace custom-metrics \
    --set appInsights.appId= \
    --set appInsights.key= \
    --set azureAuthentication.createSecret=true

Error: release sample-release2 failed: customresourcedefinitions.apiextensions.k8s.io "custommetrics.azure.com" already exists
```

Could you check if you have a helm install of the adapter already already (`helm list`)?  Another thing you can check is `kubectl get custommetrics`. If the metric adapter CRD's are already installed you will get an answer back like `No resources found.`, otherwise you get `error: the server doesn't have a resource type "custommetric"`

If it is already installed you can either uninstall it or deploy the adapter with out the CRD's (would have to modify the helm deployment to make sure the CRD's are not included).

**Comment by jsturtevant** [comment]
Closing.  If you have further questions feel free to create new issue or re-open with new information
